T: 1
amp: false
batch_size: 64
dataset: cifar10
num_classes: 10
arch: resnet18
model_depth: 28
model_width: 2
ema_decay: 0.999
eval_step: 1024
expand_labels: false
gpu_id: 0
lambda_u: 1
local_rank: -1
lr: 0.03
mu: 7
nesterov: true
no_progress: false
num_labeled: 4000
num_workers: 4
opt_level: O1
out: result
resume: ''
seed: null
start_epoch: 0
threshold: 0.95
# total_steps: 1048576
total_steps: 20480
use_ema: true
warmup: 0
wdecay: 0.0005
test: true